Feature/osato/1
ShiotaYoshiaki/Vue_Rental_Space pull request #1
Opened 2020-07-11 02:40 UTC by osato-pg

プロジェクトを作りました。
https://app.asana.com/0/1183711201310168/list

2020-07-11 03:47 UTC, ShiotaYoshiaki requested changes

2020-07-11 03:47 UTC, ShiotaYoshiaki commented on my-project/package.json
> +    "vue-template-compiler": "^2.6.11"
^や~は削除してください

2020-07-13 00:46 UTC, osato-pg commented on my-project/package.json
> +    "vue-template-compiler": "^2.6.11"
ご指摘いただいた文字修正完了しました。

2020-07-15 11:18 UTC, ShiotaYoshiaki requested changes
my-projectのファイル名をfrontに変えてください

2020-07-15 11:18 UTC, ShiotaYoshiaki commented on my-project/package.json
> +  "name": "my-project",
`my-project`ではなく、`front`のほうがいいと思います
今後はAPI, Batchなどの処理が入るので、他のmy-projectの箇所も同様に変更してください

2020-09-13 02:54 UTC, merged